### ISSUE TITLE
[簡章調查] 二技學制的名額調整頁面

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#11]

**Comment by x3388638** [comment]
https://github.com/0verseas/0verSchool/commit/12bcec06091e1594d070ff1d38d088989ba8a485
https://github.com/0verseas/0verSchool/commit/f2a40273ac13b4cc5a1283b517c8f6d41382ac5e
https://github.com/0verseas/0verSchool/commit/c09b4dca674bab18a01dad0c179bf0df56616a8d
https://github.com/0verseas/0verSchool/commit/9ca56ef77149f6033a10e2489c67363cc9db33eb

**Comment by ZerNico** [comment]
@x3388638 @pagaiba
