### ISSUE TITLE
[簡章調查] 儲存時不檢查必填欄位是否有填

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#16]

**Comment by lemon5920** [comment]
[800eba3](https://github.com/0verseas/0verSchool/commit/800eba3080242f05c7bc019a5b3cfad76c8a90b4)

**Comment by sunnyworm** [comment]
@lemon5920 
可以用線上機器 editor1 帳號測試看看嗎？
目前有更新到最新版，
但是我測起來還是會需要有輸入值才能夠儲存。

錯誤訊息為「有欄位輸入錯誤，請重新確認。」

**Comment by sunnyworm** [comment]
sorry 沒有更新到最新，目前是 API 回 400 error

**Comment by lemon5920** [comment]
線上更新囉 <3
400 error 是 API 要求「是否招收中五生」、「是否單獨招收僑生（自招）」必須不能被勾選
請 API 這兩項改為可勾選

**Comment by zxp86021** [comment]
fix at https://github.com/0verseas/0verAPI/commit/d53df3d0843ef19140f51ff7d13fdec5b1656b01

**Comment by lemon5920** [comment]
fix at [d05f9db](https://github.com/0verseas/0verSchool/commit/d05f9db58877599d748626713f6f91f67aaf357e)
