### ISSUE TITLE
[簡章調查] 在 IE 11 & EdgeHTML 14 上 fetch 有問題

### ISSUE THREAD

**Issue by YuerLee** [0verseas/0verSchool#21]
不會自動跳轉，初步看是 fetch 拋出一個 TypeMisMatchError。

**Comment by lemon5920** [comment]
本服務僅支援 Google chrome 與 Mozilla firefox。
欲在 Microsoft 瀏覽器運行，請充值解鎖該功能。

**Comment by lemon5920** [comment]
Edge & IE 使用 fetch() 的 response 在 status != 2xx 均為 TypeMismatchError。
目前看起來 MS 是「聲稱」他們有解決這項問題。

**Comment by YuerLee** [comment]
是 non-Ascii 的問題嗎？
是不是修好了，可是還沒發布？

**Comment by lemon5920** [comment]
non-Ascii 是什麼？輸入的問題嗎？
已登入為例，帳號密碼正確是沒有問題的。
輸入錯誤就會出現 TypeMismatchError。

這篇好像有提到 Edge Team 修好了
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8653298/
但是目前看起來就是還沒修好。

這篇的瀏覽器版本、錯誤狀況很雷同
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8546263/
但是 Edge Team 回應沒看到這個錯誤，
給出的官方寫法沒有指出如何 catch status，
支援度列表很雞助。

所以要開始寫 AJAX 了嗎？

**Comment by YuerLee** [comment]
改引入 https://github.com/github/fetch ，不用瀏覽器自帶的如何？

**Comment by lemon5920** [comment]
我這裡測試結果一樣。

**Comment by YuerLee** [comment]
Scott L. Apr 28, 2017 (MICROSOFT EDGE TEAM)
This has been fixed in the Creators Update (Edge 15.15063).

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8546263/#comment-12

**Comment by ZerNico** [comment]
@passerbyid You totally know alot about html and JavaScript and css right?
