### ISSUE TITLE
在學士班名額分配頁面需要送出使用者填寫的學士班自招總額

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#23]

**Comment by YuerLee** [comment]
這個 @x3388638 做好了。

**Comment by sunnyworm** [comment]
![screenshot from 2017-06-27 12-13-55](https://user-images.githubusercontent.com/8233294/27570626-31aba6ce-5b32-11e7-9dc1-46c8a780c620.png)

**Comment by sunnyworm** [comment]
不好意思又看錯了
