### ISSUE TITLE
必填的紅色不好看

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#46]
交給良良了

**Comment by ast850328** [comment]
@sunnyworm  老鐵，怎樣才算好看呢？ 20點求解

**Comment by bluet** [comment]
886 前面是不是該有 + 號？

**Comment by ast850328** [comment]
2de30187b04e67f5aa28d00e51d076dff6446d24
5675b819a655205b61e638c029859c2c4f48f41c
64c3f359ca3fc4f15b36483749156b8070428cdd

老鐵～改好了
