### ISSUE TITLE
[簡章調查] 除了英文校名、英文系名之外的「英文」欄位都不必必填

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#6]

**Comment by lemon5920** [comment]
[fa81a4e](https://github.com/0verseas/0verSchool/commit/fa81a4e8d13270faaa5f077d87f2ab01a685ab8e)

**Comment by sunnyworm** [comment]
@lemon5920 
editor1
獎學金的英文名稱、英文網址不填也是出現錯誤訊息，
錯誤訊息為「有欄位輸入錯誤，請重新確認。」

**Comment by sunnyworm** [comment]
sorry 沒有更新到最新，目前是 API 回 400 error

**Comment by lemon5920** [comment]
線上更新囉 <3
400 error 是 API 要求「是否招收中五生」、「是否單獨招收僑生（自招）」必須不能被勾選
請 API 這兩項改為可勾選

**Comment by lemon5920** [comment]
fix at [d05f9db](https://github.com/0verseas/0verSchool/commit/d05f9db58877599d748626713f6f91f67aaf357e)

**Comment by sunnyworm** [comment]
只要非必填但是有填的欄位，有格式驗證的就會驗證（如網址）
