### ISSUE TITLE
[簡章調查] 讓使用者修改自己的帳號資訊

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#7]
至少要可以改名字跟 email

**Comment by YuerLee** [comment]
@sunnyworm 可以讓編輯改自己的密碼嗎？

**Comment by ast850328** [comment]
@sunnyworm 好像搞定了 在 #24

**Comment by YuerLee** [comment]
經 @x3388638 review，現已 merge。 
9995d4efed5c2a157a3264ec6d08e0bb76421518
