### ISSUE TITLE
[簡章調查] 學制頁面的系所列表需要接上

### ISSUE THREAD

**Issue by sunnyworm** [0verseas/0verSchool#9]

**Comment by lemon5920** [comment]
於 [dd46861](https://github.com/0verseas/0verSchool/commit/dd46861b38359d962d0958cfe5cc37347d1f6e1e)

**Comment by lemon5920** [comment]
碩班、博班的列表搜尋需修復
`#` 改為 `sort_order`

**Comment by lemon5920** [comment]
`sort_order` 問題
fix [a3678bb](https://github.com/0verseas/0verSchool/commit/a3678bbd7d550bab15773f4923e1f65e22cca849)

**Comment by Kuberrocks96** [comment]
@lemon5920 Faq dopeos

**Comment by dg28gadhavi** [comment]
@lemon5920 He is everywhere

**Comment by Kuberrocks96** [comment]
@lemon5920 That's a different story

**Comment by mohancm100** [comment]
@lemon5920 Yeah LoL😂😂😂
